version: '2'

services:

  pops-broker:
    build: ./
    image: centos-nodejs
    command: top -b
    environment:
      TERM: xterm
    #ports:
    #  - "1883:1883"
    #  - "9001:9001"
    volumes:
      - ./data:/mnt/dev
    restart: always
