#!/bin/bash

# set this to your active development branch
develop_branch="develop"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# only check commit messages on main development branch
# [ "$current_branch" != "$develop_branch" ] && exit 0

# regex to validate in commit msg
commit_regex='(^(fix|feat|docs|style|refactor|perf|test|chore)\([a-zA-Z]*\)\: )|^WIP: '
error_msg="Aborting commit. Please respect angular commit convention
format: <fix|feat|docs|style|refactor|perf|test|chore>(<scope>): <subject>
        <BLANK LINE>
        <body>
        <BLANK LINE>
        <footer>
doc: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines
"
message=$(cat $1)

RESULT=$(echo $message | grep -E "$commit_regex")

if [ -z "$RESULT" ]; then
    echo "$error_msg
message: $message" >&2
    exit 1
fi
